/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Convert Color Space
 #	author : miyako
 #	2015/10/16
 #
 # --------------------------------------------------------------------------------*/



// --- Convert Color Space
void Convert_color_space(sLONG_PTR *pResult, PackagePtr pParams);
